### ISSUE TITLE
[cli] `sui move test` bug with transitive dependency

### ISSUE THREAD

**Issue by WayneAl** [MystenLabs/sui#23739]
## Steps to Reproduce Issue

Weird testing error happened when I was using the Suilend (https://github.com/Typus-Lab/suilend) as dependency.

The `new_price_info_object_for_testing` of Pyth is a test only public function and it works in Suilend's testing cases. 
![Image](https://github.com/user-attachments/assets/ca4c2348-3cda-45dd-bebc-cc44101da87b)

However, we fail running the tests when we use Suilend as our Dov dependency.
![Image](https://github.com/user-attachments/assets/b4fad89d-d213-48f7-b35b-4ac45079a985)

And I observed this error may happen in very transitive dependency.
A use B as dependency and B use C as dependency if C has `test_only` public function.
B will work fine in test, but A will get the `unbound module member` error.

## Expected Result

Expected A will work fine in test

## Actual Result

A got error while running `sui move test`

## System Information

sui version: `sui 1.56.3-4b16586bb037`

**Comment by mdgeorge4153** [comment]
I set up a little test case and wasn't able to reproduce on 1.56.2 or 1.57 - https://github.com/mdgeorge4153/repro_23739; I'll try again with a suilend dependency

**Comment by mdgeorge4153** [comment]
I added an example that depends on suilend to the above repository, and it also builds with `sui 1.56.2-2cd6aa1238d6` and `sui 1.57.0-3b96ab72dd5d`. I wonder if you could modify some of those files to reproduce your error?

**Comment by WayneAl** [comment]
Hello sir, I found it happened with `override=true`

Here is my [example code](https://github.com/Typus-Lab/suilend/tree/issue_example/issue_example), if I use 
```
[dependencies.Pyth]
git = "https://github.com/Typus-Lab/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-mainnet"
override = true
```
the error will show up.

Because we integrate 3 different lending protocols all use Pyth in different rev, we need to use `override=true`.

**Comment by mdgeorge4153** [comment]
Ah, the problem seems to be that the version of pyth that you override to doesn't have those functions - even though upgraded versions have to maintain backwards compatibility for non-test functions, they are allowed to add and remove test-only functions as they please. I'll ask around and see if there's a recommended workaround.

**Comment by mdgeorge4153** [comment]
It seems like the new test extension feature in the alpha edition of move 2024 might solve your problem. You can use it to add back in the test functions that were removed in Pyth. To do so, you will need to set `edition = "2024.alpha"` in your `Move.toml`, and then add an extension module to your package (see [here](https://github.com/mdgeorge4153/repro_23739) for the example):
```move
#[test_only]
extend module pyth::price_info;

#[test_only]
public fun new_price_info_object_for_testing(
  price_info: PriceInfo,
  ctx: &mut TxContext
): PriceInfoObject {
    assert!(false, 1);
    PriceInfoObject {
      id: object::new(ctx),
      price_info
    }
}


#[test_only]
public fun update_price_info_object_for_testing(
  price_info_object: &mut PriceInfoObject,
  price_info: &PriceInfo
) {
  assert!(false, 1)
}
```

This allows you to add test_only functions to Pyth. I've made them assert false here because I'm assuming that your code doesn't call test functions in suilend that call the missing functions in Pyth. If you are, you may need to understand more about the functions that were removed.

Extension modules are an alpha feature, so there may be some rough edges and the behavior might change.

**Comment by WayneAl** [comment]
I ran your `suilend_example`, but I met some errors. Seems extend not works for me?

<img width="2282" height="890" alt="Image" src="https://github.com/user-attachments/assets/8bbc9dbb-0fb5-4838-86b2-cfea629309c8" />

**Comment by mdgeorge4153** [comment]
I was using `sui 1.57.0-3b96ab72dd5d`; module extensions are a brand new feature - are you using an earlier version?

**Comment by mdgeorge4153** [comment]
Marking this as resolved; feel free to reopen if a later version of the sui CLI hasn't fix it.
