### ISSUE TITLE
Math example not compiling

### ISSUE THREAD

**Issue by galic1987** [MystenLabs/sui#11671]
## Steps to Reproduce Issue

sui client publish ./sui_programmability/examples/math --gas 0x44e02759a6c718832e9a4deec4c7c8b3ddf281c276cfab7b8cf1557d0cfa6370  --gas-budget 300000000 --skip-dependency-verification --with-unpublished-dependencies

e.g.
1. Call function <function call>.
2. Use return value and call <other function call>.

## Expected Result

Deployed! 

e.g.
Expected <other function call> to return 42.

## Actual Result

[warn] Client/Server api version mismatch, client api version : 0.33.0, server api version : 1.0.0
INCLUDING DEPENDENCY Sui
INCLUDING DEPENDENCY MoveStdlib
BUILDING Math
error[E03003]: unbound module member
   ┌─ ./sources/ecdsa.move:29:20
   │
29 │             value: ecdsa_k1::keccak256(&data),
   │                    ^^^^^^^^^^^^^^^^^^^ Invalid module access. Unbound function 'keccak256' in module '(sui=0x2)::ecdsa_k1'

error[E03003]: unbound module member
   ┌─ ./sources/ecdsa.move:38:20
   │
38 │             value: ecdsa_k1::ecrecover(&signature, &hashed_msg),
   │                    ^^^^^^^^^^^^^^^^^^^ Invalid module access. Unbound function 'ecrecover' in module '(sui=0x2)::ecdsa_k1'

error[E03003]: unbound module member
   ┌─ ./sources/ecdsa.move:55:22
   │
55 │         let pubkey = ecdsa_k1::ecrecover(&signature, &hashed_msg);
   │                      ^^^^^^^^^^^^^^^^^^^ Invalid module access. Unbound function 'ecrecover' in module '(sui=0x2)::ecdsa_k1'

error[E03003]: unbound module member
   ┌─ ./sources/ecdsa.move:68:22
   │
68 │         let hashed = ecdsa_k1::keccak256(&uncompressed_64);
   │                      ^^^^^^^^^^^^^^^^^^^ Invalid module access. Unbound function 'keccak256' in module '(sui=0x2)::ecdsa_k1'

error[E04016]: too few arguments
   ┌─ ./sources/ecdsa.move:87:49
   │
87 │         event::emit(VerifiedEvent {is_verified: ecdsa_k1::secp256k1_verify(&signature, &public_key, &hashed_msg)});
   │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │                                                 │                         │
   │                                                 │                         Found 3 argument(s) here
   │                                                 Invalid call of '(sui=0x2)::ecdsa_k1::secp256k1_verify'. The call expected 4 argument(s) but got 3

Failed to build Move modules: Compilation error.

## System Information

* OS: Mac Silicon Ventura 13.2.1
* Compiler: 0.1.0

**Comment by stefan-mysten** [comment]
@galic1987 This example works on Sui v1.10.1 (I was unable to reproduce your error). If this is still an issue, please create a new GitHub issue.
