### PR TITLE
[sui-core/ gate some util methods]

### PR DESCRIPTION
**Pull request by suiwombat**
Summary:

* unable to build sui-core due to a cfg gate.
* build error caused by https://github.com/MystenLabs/sui/commit/c9a1414d6860e1a94682f05738eccb812c965a73
* hack in some gates via #[cfg(feature = "test-utils")] to let the rest of the repo build again.

Test Plan:

fixes build error:

```
error[E0432]: unresolved import `sui_types::utils`
  --> crates/sui-core/src/authority/authority_test_utils.rs:12:5
   |
12 |     utils::to_sender_signed_transaction,
   |     ^^^^^ could not find `utils` in `sui_types`

For more information about this error, try `rustc --explain E0432`.
```

This is due to how it's gated in lib.rs:

```
#[cfg(feature = "test-utils")]
#[path = "./unit_tests/utils.rs"]
pub mod utils;
```

cargo build

## Description 

Describe the changes or additions included in this PR.

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by suiwombat** [comment]
defer to https://github.com/MystenLabs/sui/pull/11102

**Comment by future0787** [comment]
[](url)
