### ISSUE TITLE
webpki error compiling rustls-platform-verifier v0.3.4 from git

### ISSUE THREAD

**Issue by thegreatyak** [MystenLabs/sui#21509]
Hello,

When I try to install the devnet branch using cargo command:
cargo install --git https://github.com/MystenLabs/sui.git --branch devnet sui --force

I get this compiler error:

Compiling rustls-platform-verifier v0.3.4
error[E0277]: the trait bound `webpki::Error: std::error::Error` is not satisfied
   --> /home/yak/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-platform-verifier-0.3.4/src/verification/others.rs:234:40
    |
234 |             other_err.0.downcast_ref::<webpki::Error>()
    |                         ------------   ^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `webpki::Error`
    |                         |
    |                         required by a bound introduced by this call
    |
note: required by a bound in `<(dyn std::error::Error + Send + Sync + 'static)>::downcast_ref`
   --> /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/error.rs:271:5

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rustls-platform-verifier` (lib) due to 1 previous error
warning: build failed

Do you have a workaround for this?

Regards,
Yak

**Comment by xdhdxv** [comment]
try to add it to your Cargo.toml

rustls-webpki = "0.102"

**Comment by getong** [comment]
cannot compile with rust stable 1.85.0,  see https://github.com/subquery/network-indexer-services/pull/619
also see https://github.com/subquery/network-indexer-services/actions/runs/13915118053/job/38936657345

**Comment by edward-squad** [comment]
> try to add it to your Cargo.toml
> 
> rustls-webpki = "0.102"

that fixes it.

**Comment by getong** [comment]
> > try to add it to your Cargo.toml
> > rustls-webpki = "0.102"
> 
> that fixes it.

Thanks, it works

**Comment by thegreatyak** [comment]
> try to add it to your Cargo.toml
> 
> rustls-webpki = "0.102"

Worked for me, thank you!
